### ISSUE TITLE
Add visual cues to hyperlinks

### ISSUE THREAD

**Issue by bhaugen** [ahdinosaur/linked-data-browser#10]
Like the usual blue font with underline.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/10.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
