### ISSUE TITLE
Make breadcrumbs into hyperlinks

### ISSUE THREAD

**Issue by bhaugen** [ahdinosaur/linked-data-browser#11]
I really like the history of what I've explored on the top, but would love it if each of those was hyperlinked as a LDB focus so I could refocus on it.

For example:
http://nrp.webfactional.com/api/agent-jsonld/ success
http://nrp.webfactional.com/api/agent-type-lod/Organization redirect
http://nrp.webfactional.com/api/agent-type-lod/Organization/ success
http://nrp.webfactional.com/api/agent-type-lod/Network redirect
http://nrp.webfactional.com/api/agent-type-lod/Network/ success
http://nrp.webfactional.com/api/agent-lod/6/ success
http://nrp.webfactional.com/api/agent-relationship-lod/2/ success
http://nrp.webfactional.com/api/agent-lod/7/ success

They're not live hyperlinks. I'd love it if the "success" ones were, and if I clicked on one, it would refocus the LDB on that.

**Comment by ahdinosaur** [comment]
keen for breadcrumbs. the "history" at the top is a list of graphs that have been fetched, which is slightly different.

**Comment by bhaugen** [comment]
I understand that technically they are not ~exactly~ breadcrumbs, so I would like to separate my suggestion from that word. The suggestion is to make the list of graphs clickable so I could refocus the LDB on that graph without hitting the back button until I get there. Not a big deal, I can backpedal easily enough.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/11.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
