### ISSUE TITLE
duplicate items emerge after following my nose in a cycle

### ISSUE THREAD

**Issue by bhaugen** [ahdinosaur/linked-data-browser#12]
focus @id http://nrp.webfactional.com/api/agent-jsonld/
http://nrp.webfactional.com/api/agent-jsonld/
http://nrp.webfactional.com/api/agent-jsonld/success
http://nrp.webfactional.com/api/agent-type-lod/Organizationredirect
http://nrp.webfactional.com/api/agent-type-lod/Organization/success
http://nrp.webfactional.com/api/agent-type-lod/Networkredirect
http://nrp.webfactional.com/api/agent-type-lod/Network/success
http://nrp.webfactional.com/api/agent-lod/6/success
http://nrp.webfactional.com/api/agent-relationship-lod/2/success
http://nrp.webfactional.com/api/agent-lod/7/success
view as: nodelist

nrp:agent-lod/7/

vf:label
"Mikorizal Software"@en
"Mikorizal Software"@en

rdf:type
nrp:agent-type-lod/Group
nrp:agent-type-lod/Group

nrp:agent-relationship-type-lod/hasMember
nrp:agent-relationship-inv-lod/1/
nrp:agent-relationship-inv-lod/2/
nrp:agent-relationship-lod/2/

rdf:type
vf:Relationship
vf:Relationship

vf:subject
nrp:agent-lod/6/
nrp:agent-lod/6/

**Comment by bhaugen** [comment]
Here's the node in the cycle where the dups first emerge. Note, I have no idea if this is data, code, or a combo. [But I don't see the dups in the data...]

http://nrp.webfactional.com/api/agent-jsonld/ success
http://nrp.webfactional.com/api/agent-lod/8/ success
http://nrp.webfactional.com/api/agent-relationship-inv-lod/3/ success

nrp:agent-relationship-inv-lod/3/

vf:subject
nrp:agent-lod/8/
nrp:agent-lod/8/

vf:relationship
nrp:agent-relationship-type-lod/hasAffiliate
nrp:agent-relationship-type-lod/hasAffiliate

vf:object
nrp:agent-lod/1/
nrp:agent-lod/1/
owl:inverseOf

nrp:agent-relationship-lod/3/

rdf:type
vf:Relationship
vf:Relationship

**Comment by ahdinosaur** [comment]
yeah this seems to happen if you fetch the same triples from different graphs. technically they are separate quads, so it doesn't make sense to throw them out right away, but we should probably de-dupe while we display. the nuances of this are related to https://github.com/valueflows/linked-data-browser/issues/4.

**Comment by bhaugen** [comment]
Not a big problem, I just noted and reported. But if they are technically separate quads, could that be shown somehow?

**Comment by fosterlynn** [comment]
Interesting, these are probably from a different graph, but probably from the same data source (same namespace?).  Wondering if people make that distinction in the provenance world.  

(This is idle curiosity right now, not intending to look it up or ask anyone else to look it up right now.)  #4

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/12.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
