### ISSUE TITLE
follow your nose

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/linked-data-browser#2]
reference: http://patterns.dataincubator.org/book/follow-your-nose.html

right now we fetch only the entity in focus, maybe we should be fetching more optimistically.

**Comment by bhaugen** [comment]
I'd be happy with links to follow with my own nose...

**Comment by ahdinosaur** [comment]
@bhaugen what do you mean?

**Comment by bhaugen** [comment]
@ahdinosaur sorry to be cryptic. I read that article to say,

> Identify additional useful links within the available data, and then de-reference those URIs in turn to find the additional data.

I would be happy with just the additional useful links, without your de-referencing them to find the additional data.

More clear?

**Comment by ahdinosaur** [comment]
@bhaugen yeah, thanks for the clarification. is that not how it works already?

**Comment by ahdinosaur** [comment]
ohh wait nevermind, yeah i forgot the links are really naive at the moment (purely based on the quads), need to implement https://github.com/valueflows/linked-data-browser/issues/5, https://github.com/valueflows/linked-data-browser/issues/6, https://github.com/valueflows/linked-data-browser/issues/7, and possibly others.

**Comment by bhaugen** [comment]
@ahdinosaur you know, a lot of the links do work now. I just didn't recognize them as links. No visual cues. Cursor hover does work, though. I could walk quite aways through this one:
http://nrp.webfactional.com/api/agent-jsonld/

A lot of errors on the links in this one:
https://rawgit.com/valueflows/agent/master/examples/enspiral.jsonld

See #10 

But now that I know this, it makes it much much better. Becomes a real explorer.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
