### ISSUE TITLE
allow changing language: en, es, de, fr, it etc

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/linked-data-browser#3]

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
