### ISSUE TITLE
smushing

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/linked-data-browser#5]
reference: http://patterns.dataincubator.org/book/smushing.html

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/5.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
