### ISSUE TITLE
support inverses

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/linked-data-browser#7]
http://www.jenitennison.com/2009/12/05/creating-linked-data-part-v-finishing-touches.html#inverses

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
