### ISSUE TITLE
support queries

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/linked-data-browser#9]
https://github.com/RubenVerborgh/N3.js#storing
https://github.com/LinkedDataFragments/Client.js
http://client.linkeddatafragments.org/
http://patterns.dataincubator.org/book/named-query.html
http://patterns.dataincubator.org/book/parameterised-query.html

**Comment by fosterlynn** [comment]
@ahdinosaur hey looks like you're cooking' on this stuff!  Looking forward to seeing it! :smile:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-browser/-/issues/9.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
